[platformio]
default_envs = receive-evaluate-unlock
src_dir = MFOC_Badge_Base_Station

[env]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    z3t0/IRremote@^4.4.1
build_flags =
    -Wall
    -Wextra

[env:receive-only]
build_flags =
    ${env.build_flags}
    -DMFOC_STATION_ROLE=0

[env:receive-evaluate-unlock]
build_flags =
    ${env.build_flags}
    -DMFOC_STATION_ROLE=1

[env:transmit-unlock]
build_flags =
    ${env.build_flags}
    -DMFOC_STATION_ROLE=2
