[platformio]
default_envs = uno
core_dir = ${sysenv.LOCALAPPDATA}/PlatformIO/mfoc-badge-base
src_dir = Station04_Shadow_Light

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps =
    z3t0/IRremote@^4.4.1
build_flags =
    -Wall
    -Wextra
